version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin public.ecr.aws/q6n5w1i7/sample
  pre_build:
    commands:
      - echo "Starting build process for Flask App..."
      - REPO_URI=public.ecr.aws/q6n5w1i7/sample
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t flask-app .
      - docker tag flask-app:latest $REPO_URI:$IMAGE_TAG
      - docker tag flask-app:latest $REPO_URI:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
artifacts:
  files: '**/*'
  discard-paths: yes
