[
  {
    "name": "flaskapp",
    "imageUri": "713881800587.dkr.ecr.ap-northeast-1.amazonaws.com/flaskapp"
  },
  {
    "name": "email-api",
    "imageUri": "713881800587.dkr.ecr.ap-northeast-1.amazonaws.com/mailapi"
  }
]
