apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: kavinraj2k1/pipelineexample # Replace with your app's Docker image (e.g., myrepo/myflaskapp:latest)
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort  # Exposes the Flask app externally
  selector:
    app: flask-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000  # Port to expose the Flask app on

