apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
      - name: email-api
        image: 713881800587.dkr.ecr.ap-northeast-1.amazonaws.com/mailapi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: email-api
spec:
  type: ClusterIP  
  selector:
    app: email-api
  ports:
    - port: 5000
      targetPort: 5000

