apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
      - name: email-api
        image: kavinraj2k1/emailapi:latest  # Replace with your email API's Docker image (e.g., myrepo/myemailapi:latest)
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: email-api
spec:
  type: ClusterIP  # This keeps the email API internal to the cluster
  selector:
    app: email-api
  ports:
    - port: 5000
      targetPort: 5000

